### ISSUE TITLE
Ability to change Account Id for Technical Committee Membership

### ISSUE THREAD

**Issue by dharjeezy** [polkadot-fellows/help-center#1]
I lost access to my former account id  which is part of the technical committee fellow, my former account id is  `H5BuqCmucJhUUuvjAzPazeVwVCtUSXVQdc5Dnx2q5zD7rVn`, This is my Polkadot account id I want to change to `12GyGD3QhT4i2JJpNzvMf96sxxBLWymz4RdGCxRH5Rj5agKW`.

**Comment by bkchr** [comment]
We don't really have functionality for this right now, as far as I can see. I would propose we add some dispatchable to ranked collective for exchanging a member. The dispatchable should require that the proper has a rank that is at least as high as the one that should be exchanged. The dispatchable should require a custom origin. Then we should add some track for this exchange that requires a high participation.

@dharjeezy can you please do this?

**Comment by dharjeezy** [comment]
Hello @bkchr Ok. I can do this.

**Comment by dharjeezy** [comment]
So, i am thinking, should we do it such that when we want to exchange a member, we remove the old member, and then we add the new member with the same rank as the old member?

**Comment by bkchr** [comment]
You mean implementation wise?

**Comment by dharjeezy** [comment]
> You mean implementation wise?

Yes, i mean implementation wise. @bkchr

**Comment by bkchr** [comment]
Yes sounds good then!
