### ISSUE TITLE
Setup docs that include everything a fellowship member or candidate needs to know

### ISSUE THREAD

**Issue by xlc** [polkadot-fellows/help-center#2]
I would like to have this repo (or some other repo) to be the main source of information for all fellowship members and candidates.

Here is an incomplete list of topics that should be included. We do have some of those information available somewhere, and we should have them gathered to a single place.

- How to become a candidate
- How to not get demoted. i.e. the responsibilities. (for rank 1, 2, 3, and so on) 
- How to get promoted (to rank 1, 2, 3, and so on)
- How to setup identity and link to github handle
- How to use review bot and merge bot and rfc bot
- How to find a mentor
- The online and offline events (e.g. the OpenDev Monthly Call)
- Meeting notes

**Comment by ggwpez** [comment]
I think we should document those things and then publish them in some way (see #4). Maybe a wiki could work.  
Or we write everything into md files and then just render them nicely.

**Comment by wirednkod** [comment]
> Or we write everything into md files and then just render them nicely.

MD files could work as they can easily passed into a React page (what I am already putting together for this - see #4 )

**Comment by wirednkod** [comment]
It would be great if you can point anywhere where the content above can be found;
If you are not sure then I will open some issues in order to address the content and suggest to the ones that showed interest on helping that they can take over for the content creation;

**Comment by xlc** [comment]
Most of them will be in manifesto (how to join & promote etc) but someone have to create a more easily accessible format.
And some more existing docs that I can find:
https://github.com/polkadot-fellows/runtimes/blob/main/docs/on-chain-identity.md
https://github.com/polkadot-fellows/RFCs#bots
https://wiki.polkadot.network/docs/learn-polkadot-opengov#the-polkadot-technical-fellowship

**Comment by wirednkod** [comment]
Thank you @xlc . I have created a very first demo-draft [here](https://wirednkod.github.io/dashboard) and I will try to either create that content or open issues of the tasks that needs to be done for external help.
Will go through the docs and try to see what I can do (e.g. last link you provided is the `Overview` page of the link given above)

**Comment by wirednkod** [comment]
@xlc @ggwpez the very first draft is here: https://polkadot-fellows.github.io/dashboard

I have opened the [relevant issues](https://github.com/polkadot-fellows/dashboard/issues/) as described above so I believe this can close now - and transfer the conversation to the [dashboard repository](https://github.com/polkadot-fellows/dashboard/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)

**Comment by xlc** [comment]
Few more things we need:
- Describe the fellowship core pallet and salary pallet
- How members should interact with the fellowship pallet and salary pallet

**Comment by anaelleltd** [comment]
Hello all,

I will be working on gathering some specific resources for candidates with the aim to help them go from 0 to I.

Concretely, this will involve:
 - [x] A list of low-level projects for candidates aiming for Rank I.
 - [x] A detailed overview of the promotion process.

The scope of these resources will be limited to the approved areas/repos mentioned in this [issue](https://github.com/polkadot-fellows/help-center/issues/6).

If you have any other suggestions about what else can be provided to support candidates, please let me know!
Thanks.

**Comment by anaelleltd** [comment]
All important Fellowship processes and operations are now documented on the Polkadot Technical Fellowship website: https://polkadot-fellows.xyz/
