### ISSUE TITLE
SECURITY BUG BOUNTY FOR POLKADOT<->KUSAMA BRIDGE - FELLOWSHIP AS CURATOR

### ISSUE THREAD

**Issue by VinceCorsica** [polkadot-fellows/help-center#5]
Hi
I am reaching out as I am planning to launch soon a Security BugBounty with as a scope the bridge between Polkadot and Kusama. And in that context I am looking for curators.

SCOPE:
For that specific bounty, most of operational task will be perform by Parity Security team including:
- 1. reviewing the security bounty request from the Whitehat
- 2. after triage, giving it to the engineering team to have it fixed, 
- 3. after remediation, checking if it fixes the root cause in partnership with engineering team involved, the whitehat and if required with external security audit firm
- 4. then to propose the reward level to the curators
- 5. eventually to communicate to the community about the bug and remediation

The key activities of the curators will be the following:
- oversight of the end to end process effectiveness including quality and speed to manage requests
- support the triage for edge cases based on expertise required
- decide the reward level based on the criticality and reward framework/banding within the referenda
- executing the payment onchain to the Whitehat when required

MEMBERS:
To ensure the successful implementation of this bounty, the curators will be at least 5, representing different members of the Polkadot ecosystem, bringing diverse forms of expertise:
- At least 2 curators with expertise on Bridges as this is the focused area of this bug bounty
- At least 2 curators with security expertise as this bounty is about security bug

to complete the members, having the Fellowship represented by someone on that bounty will be very beneficial from multiple perspectives

I am available if you need more details

**Comment by bkchr** [comment]
@seunlanlege you maybe want to do this?

**Comment by seunlanlege** [comment]
> @seunlanlege you maybe want to do this?

Yeah i can help out

**Comment by VinceCorsica** [comment]
> > @seunlanlege you maybe want to do this?
> 
> Yeah i can help out

Thanks a lot. I reached out via Element to continue the conversation

**Comment by anaelleltd** [comment]
Curators for the the bounties have been finalised and set up:
- Polkadot:  https://polkadot.subsquare.io/treasury/bounties/44?tab=timeline
- Kusama: https://kusama.subsquare.io/treasury/bounties/27?tab=timeline
