### ISSUE TITLE
Tracking the implementation of RFCs

### ISSUE THREAD

**Issue by ggwpez** [polkadot-fellows/help-center#7]
The Fellowship commits to the implementation of each merged RFC. Currently many of the RFCs are implemented by their creators, but this cannot be assumed in general. Especially not for external RFCs (eg [#20](https://github.com/polkadot-fellows/RFCs/pull/20)). 
I wonder if we should create an issue after each merged RFC to track its implementation. This could be done by the RFC merge bot.

You think this could be useful?

**Comment by bkchr** [comment]
For the RFC you linked there exists an issue :D https://github.com/polkadot-fellows/runtimes/issues/100

What would you expect to be the advantage of creating an issue per RFC? I mean how would this help?

**Comment by anaelleltd** [comment]
Hello all,

I will be looking into setting up a tracker for RFCs as described [here](https://github.com/users/anaelleltd/projects/1?pane=issue&itemId=60634194).

I would love to have your input on the following questions:
1) What are the review requirements for RFCs? (i.e minimum n. of participants, rank of reviewers, technical feedback)
2) What are the timelines for submitting RFCs for vote? (i.e minimum time discussion period, rank of submitters)
3) What are known/potential blocking or fast-tracking conditions?
4) Are proposers typically in charge of implementing RFCs?
5) How often do implementers call for contributors?
6) Under which circumstances can approved RFCs become redundant/deprecated?

Cheers! 🤓

**Comment by anaelleltd** [comment]
The RFC Dashboard is now implemented (in sync with GitHub) [here](https://polkadottechnicalfellowship.notion.site/RFC-Dashboard-13396f88d0a7805c9827c7f3026fbb5e).
