### ISSUE TITLE
Fellowship secretary

### ISSUE THREAD

**Issue by bkchr** [polkadot-fellows/help-center#8]
Over the time the fellowship exists now (not that long), I and others have seen that sometimes we would need to have more help in organizing stuff etc. So, the idea arose that it would be good to have some kind of Secretary for the fellowship. Here is a preliminary list of things this person could do:

- Organization of fellowship meetings
- Help with RFCs. Get more engagement. Do some cat herding and whatever that can help to improve the process
- Help documenting processes. Help people with basic stuff.
- Some project management stuff around releases.
- Maybe help with the fellowship/opendev call.

If you have more ideas, please comment.

We would also want to pay this person. The current idea is that we probably add some secretary collective as other collectives may at some point have the same need.

**Comment by ggwpez** [comment]
Yea, will be needed even more once the retetion calls start.  
Also checking all the UI from Polkassembly/Subsquare is correct and in sync it with the manifesto.

Could also create blog posts about the fellowship? Or maybe im overstretching this 😅

**Comment by olanod** [comment]
Maybe we also need a secretarybot? a lot of tasks could be automated and perhaps we can tip candidaes/members to build tools that make processes easier ;)

**Comment by anaelleltd** [comment]
Hello all,

I have put together a **[Fellowship Ops development plan](https://docs.google.com/document/d/1ls3gG4BeDx8kTHnnNQOrcATIdAjCK49l3Np-36zojN4/edit?usp=sharing)** that I think will help address and resolve most of the issues listed on the [help-center page](https://github.com/polkadot-fellows/help-center/issues).

Please leave your comments/suggestions directly on the Google doc or here on GitHub.
Thank you!

cc @ggwpez @olanod

**Comment by ltfschoen** [comment]
> Maybe we also need a secretarybot? a lot of tasks could be automated and perhaps we can tip candidaes/members to build tools that make processes easier ;)

i'd been keen to collaborate with anyone who's interested in setting up a generative AI chatbot that's also as decentralised as possible and adopts best practice project management approaches so that stuff gets automated

**Comment by bkchr** [comment]
Another point to discuss is to give the secretary rights to create proposals on all tracks. They should not be able to vote, but to create these proposals. Currently it always requires someone from the fellowship to do this, but the pure creation of the proposal should be fine to be done by everybody. Not really "everybody", but by someone like the secretary.

**Comment by anaelleltd** [comment]
Proposal submitted and executed here: https://collectives.subsquare.io/fellowship/referenda/103

**Comment by bkchr** [comment]
Yeah welcome @anaelleltd :)
