### ISSUE TITLE
Exchange My Member Account in the Fellowship

### ISSUE THREAD

**Issue by dharjeezy** [polkadot-fellows/help-center#9]
I want to exchange my member account in the fellowship as i have lost access to my previous account. I had to work on an extrinsic so as to allow for this. This is the linked issue created sometime ago https://github.com/polkadot-fellows/help-center/issues/1

previous(current) account is: `15VsPr7y92ZFAN6zv7ELqC7eeWvJN5GT2kVozRfRuNoEZCsN`
new account is: `12GyGD3QhT4i2JJpNzvMf96sxxBLWymz4RdGCxRH5Rj5agKW`

This is the encoded call hash to `fellowshipCollective::exchangeMember()`
`0x3c0600c6f57237cd4abfbeed99171495fc784e45a9d5d2814d435de40de00991a73c0600386a4f5a0311a2834e28c84daa299fe14414137807e201a1941e502c7a784467`

**Comment by anaelleltd** [comment]
Proposal submitted and executed here: https://collectives.subsquare.io/fellowship/referenda/104
You can check your new account ID here: https://collectives.polkassembly.io/members
